### ISSUE TITLE
Views Test Result

### ISSUE THREAD

**Issue by snubeaver** [talk4u/coding#39]
# Trouble Shooting

FAIL: test_only_accessible_problem_by_logged_in_student (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 254, in test_only_accessible_problem_by_logged_in_student
    self.assertEqual(resp.status_code, 200)
AssertionError: 404 != 200

======================================================================
FAIL: test_only_accessible_problem_list_by_logged_in_student (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 232, in test_only_accessible_problem_list_by_logged_in_student
    self.assertEqual(len(resp.json()), 2)
AssertionError: 5 != 2

# /problems 하면 gym으로 redirect 되어야 하는데 모든 problem 이 다 response 됨

======================================================================
FAIL: test_only_accessible_submission_details_by_logged_in_student (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 342, in test_only_accessible_submission_details_by_logged_in_student
    self.assertEqual(resp.status_code, 200)
AssertionError: 404 != 200

======================================================================
FAIL: test_only_accessible_submissions_by_logged_in_student (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 321, in test_only_accessible_submissions_by_logged_in_student
    self.assertEqual(len(resp.json()), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_problems_by_logged_in_instructor (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 457, in test_problems_by_logged_in_instructor
    self.assertEqual(len(resp.json()), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_rank_by_logged_in_student (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 424, in test_rank_by_logged_in_student
    self.assertEqual(len(resp.json()), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_submissions_by_logged_in_instructor (api.tests.test_views.GymListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/snubeaver/swpp/coding/api/tests/test_views.py", line 384, in test_submissions_by_logged_in_instructor
    self.assertEqual(resp.status_code, 200)
AssertionError: 404 != 200

**Comment by snubeaver** [comment]
problem solved
